using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace WPFDeveloper.SourceGenerators
{
    [Generator]
    public class AutoNotifyGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG
            if (!System.Diagnostics.Debugger.IsAttached)
            {
                //System.Diagnostics.Debugger.Launch();
            }
#endif
            // 第一步：筛选出所有标记了[AutoNotify]特性的字段
            var fieldDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                predicate: static (s, _) => IsFieldWidthAttrbute(s),
                transform: static (ctx, _) => GetFieldDeclaration(ctx))
                .Where(static m => m is not null);
            //var fieldDeclarations = context.SyntaxProvider
            //    .ForAttributeWithMetadataName(
            //    "WPFDeveloper.Attributes.AutoNotifyAttribute",
            //    predicate: static (node, _) => IsFieldWidthAttrbute( node),
            //    transform: static (ctx, _) => GetFieldDeclaration1(ctx))
            //    .Where(static m => m is not null);
            // 第二步：将语法节点与编译信息组合
            var compilationAndFields = context.CompilationProvider.Combine(fieldDeclarations.Collect());
            // 第三步：生成源代码
            context.RegisterSourceOutput(compilationAndFields, static (spc, source) =>
            Execute(source.Left, source.Right, spc));

        }
        private static bool IsFieldWidthAttrbute(SyntaxNode node)
        {
            // 查找字段声明且带有特性列表的节点
            if (node is not FieldDeclarationSyntax fieldDeclaration) return false;
            // 检查是否包含任何特性
            return fieldDeclaration.AttributeLists.Count > 0;
        }
        private static FieldDeclarationSyntax? GetFieldDeclaration1(GeneratorAttributeSyntaxContext context)
        {
            try
            {
                if (context.TargetNode is not FieldDeclarationSyntax fieldDeclaration)
                    return null;
                return fieldDeclaration;
            }
            catch(Exception ex)
            {
                return null;
            }
        }
        private static FieldDeclarationSyntax? GetFieldDeclaration(GeneratorSyntaxContext context)
        {
            var fieldDeclaration = (FieldDeclarationSyntax)context.Node;
            // 检查是否包含[AutoNotify]特性
            foreach (var attributeList in fieldDeclaration.AttributeLists)
            {
                foreach(var attribute in attributeList.Attributes)
                {
                    var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol;
                    if(symbol?.ContainingType.ToDisplayString()=="WPFDeveloper.Attributes.AutoNotifyAttribute")
                    {
                        return fieldDeclaration;
                    }
                }
            }
            return null;
        }


        private static void Execute(Compilation compilation,ImmutableArray<FieldDeclarationSyntax> fields, SourceProductionContext context)
        {
            if (fields.IsDefaultOrEmpty)
                return;
            // 按类分组字段
            var groupedFields = fields.GroupBy(f => f.Parent as TypeDeclarationSyntax)
                .Where(g => g.Key is not null);
            foreach(var group in groupedFields)
            {
                var classDeclaration = group.Key!;
                var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

                if(classSymbol is null)
                {
                    continue;
                }

                // 生成类的部分类实现
                var source = GeneratePartialClass(classSymbol, [.. group], context);
                if(source is not null)
                {
                    context.AddSource($"{classSymbol.Name}_AutoNotify.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            }
        }

        private static string? GeneratePartialClass(INamedTypeSymbol classSymbol,List<FieldDeclarationSyntax> fields,SourceProductionContext context)
        {
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;

            // 检查类是否已经实现了INotifyPropertyChanged
            bool implementsINPC = classSymbol.AllInterfaces.Any(i => i.ToDisplayString() == "System.ComponentModel.INotifyPropertyChanged");

            var source = new StringBuilder();

            // 添加文件头
            source.AppendLine("//<auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine();

            // 添加using指令
            source.AppendLine("using System;");
            source.AppendLine("using System.ComponentModel;");
            source.AppendLine("using System.Runtime.CompilerServices;");
            source.AppendLine();

            // 开始命名空间和类
            source.AppendLine($"namespace {namespaceName}");
            source.AppendLine("{");

            //类声明
            source.AppendLine($"    public partial class {className}{(implementsINPC ? "" : " : INotifyPropertyChanged")}");
            source.AppendLine("    {");
            // 如果没有实现INotifyPropertyChanged，则添加实现
            if(!implementsINPC)
            {
                source.AppendLine("   #region INotifyPropertyChanged实现");
                source.AppendLine("   public event PropertyChangedEventHandler? PropertyChanged;");
                source.AppendLine();
                source.AppendLine("   protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)");
                source.AppendLine("    {");
                source.AppendLine("       PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
                source.AppendLine("    }");
                source.AppendLine("   #endregion");
                source.AppendLine();
            }
            // 为每个字段生成属性
            source.AppendLine("    #region 自动生成的属性");
            foreach (var fieldDeclaration in fields)
            {
                foreach(var variable in fieldDeclaration.Declaration.Variables)
                {
                    var fieldName = variable.Identifier.ValueText;
                    var fieldType = fieldDeclaration.Declaration.Type.ToString();

                    var attribute = GetAutoNotifyAttribute(fieldDeclaration);
                    var propertyName = GetPropertyName(attribute, fieldName);
                    var alsoNotifyFor = GetAlsoNotifyFor(attribute);

                    // 生成属性
                    source.AppendLine();
                    source.AppendLine($"    public {fieldType} {propertyName}");
                    source.AppendLine("    {");
                    source.AppendLine($"      get => this.{fieldName};");
                    source.AppendLine("      set");
                    source.AppendLine("      {");
                    source.AppendLine($"        if (!System.Collections.Generic.EqualityComparer<{fieldType}>.Default.Equals(this.{fieldName}, value))");
                    source.AppendLine("        {");
                    source.AppendLine($"          this.{fieldName} = value;");
                    source.AppendLine($"          OnPropertyChanged();");
                    // 生成额外需要通知的属性
                    if (alsoNotifyFor != null && alsoNotifyFor.Length > 0)
                    {
                        foreach (var otherProperty in alsoNotifyFor)
                        {
                            source.AppendLine($"          OnPropertyChanged(nameof({otherProperty}));");
                        }
                    }

                    source.AppendLine("        }");
                    source.AppendLine("      }");
                    source.AppendLine("    }");
                }
                
            }
            source.AppendLine("    #endregion");
            source.AppendLine("  }");
            source.AppendLine("}");

            return source.ToString();
        }
        private static AttributeSyntax? GetAutoNotifyAttribute(FieldDeclarationSyntax fieldDeclaration)
        {
            return fieldDeclaration.AttributeLists
                .SelectMany(al => al.Attributes)
                .FirstOrDefault(a => a.Name.ToString() == "AutoNotify" || a.Name.ToString() == "AutoNotifyAttribute");
        }
        private static string GetPropertyName(AttributeSyntax? attribute, string fieldName)
        {
            if (attribute?.ArgumentList == null || !attribute.ArgumentList.Arguments.Any())
            {
                // 没有指定属性名，从字段名生成
                return ToPascalCase(fieldName.TrimStart('_'));
            }

            // 尝试从特性参数获取属性名
            var firstArgument = attribute.ArgumentList.Arguments[0];
            if (firstArgument.Expression is LiteralExpressionSyntax literal && literal.Kind() == SyntaxKind.StringLiteralExpression)
            {
                return literal.Token.ValueText;
            }

            return ToPascalCase(fieldName.TrimStart('_'));
        }

        private static string[]? GetAlsoNotifyFor(AttributeSyntax? attribute)
        {
            if (attribute?.ArgumentList == null)
                return null;

            // 查找AlsoNotifyFor参数
            var alsoNotifyForArgument = attribute.ArgumentList.Arguments
                .FirstOrDefault(a => a.NameEquals?.Name.Identifier.ValueText == "AlsoNotifyFor");

            if (alsoNotifyForArgument?.Expression is ArrayCreationExpressionSyntax arrayCreation)
            {
                // 简化处理：实际应用中需要更复杂的逻辑来解析数组表达式
                return Array.Empty<string>();
            }

            return null;
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;

            return char.ToUpper(input[0]) + input.Substring(1);
        }
    }
}
