using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace WPFDeveloper.SourceGenerators
{
    [Generator]
    public class INPCIncrementalGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. 使用 ForAttributeWithMetadataName 查找所有标记了 [GenerateINPC] 的字段
            IncrementalValuesProvider<GeneratorAttributeSyntaxContext> fieldProvider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: "WPFDeveloper.Attributes.AutoNotifyAttribute",
                    predicate: static (syntaxNode, _) => syntaxNode is VariableDeclaratorSyntax, // 关注变量声明符
                    transform: static (context, _) => context // 传递完整的上下文
                );

            // 2. 将编译信息与找到的字段语法节点结合
            IncrementalValueProvider<(Compilation, ImmutableArray<GeneratorAttributeSyntaxContext>)> compilationAndFields =
                context.CompilationProvider.Combine(fieldProvider.Collect());

            // 3. 注册源生成操作
            context.RegisterSourceOutput(compilationAndFields, (sourceProductionContext, tuple) =>
            {
                var (compilation, fieldsToGenerate) = tuple;

                // 按所属的类进行分组，以便为每个局部类生成一个文件
                var groupedByClass = fieldsToGenerate
                    .GroupBy(context => ((VariableDeclaratorSyntax)context.TargetNode).FirstAncestorOrSelf<ClassDeclarationSyntax>());

                foreach (var group in groupedByClass)
                {
                    ClassDeclarationSyntax classSyntax = group.Key;
                    SemanticModel semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);
                    if (semanticModel.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol) continue;

                    string namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global";
                    string className = classSymbol.Name;
                    string? classModifiers = string.Join(" ", classSyntax.Modifiers); // 保留类的访问修饰符（如 partial）

                    // 4. 为该类中所有标记的字段生成源代码
                    StringBuilder sourceBuilder = new StringBuilder();
                    GenerateINPCForClass(sourceBuilder, namespaceName, className, classModifiers, group, semanticModel);

                    sourceProductionContext.AddSource($"{className}.INPC.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
                }
            });
        }

        private static void GenerateINPCForClass(
            StringBuilder sourceBuilder,
            string namespaceName,
            string className,
            string? classModifiers,
            IGrouping<ClassDeclarationSyntax, GeneratorAttributeSyntaxContext> fieldsGroup,
            SemanticModel semanticModel)
        {
            sourceBuilder.AppendLine($$"""
                // <auto-generated/>
                #nullable enable
                using System.Collections.Generic;
                using System.ComponentModel;
                using System.Runtime.CompilerServices;

                namespace {{namespaceName}}
                {
                    {{classModifiers}} class {{className}} : INotifyPropertyChanged
                    {
                        public event PropertyChangedEventHandler? PropertyChanged;

                        protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
                        {
                            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
                        }
                """);

            // 处理这个类中的每个标记字段
            foreach (var context in fieldsGroup)
            {
                var fieldDeclarator = (VariableDeclaratorSyntax)context.TargetNode;
                var fieldSymbol = (IFieldSymbol)context.TargetSymbol;
                var attributeData = context.Attributes.FirstOrDefault();

                GeneratePropertyForField(sourceBuilder, fieldDeclarator, fieldSymbol, attributeData, semanticModel);
            }

            sourceBuilder.AppendLine("""
                    }
                }
                """);
        }

        private static void GeneratePropertyForField(
            StringBuilder sourceBuilder,
            VariableDeclaratorSyntax fieldDeclarator,
            IFieldSymbol fieldSymbol,
            AttributeData attributeData,
            SemanticModel semanticModel)
        {
            string fieldName = fieldSymbol.Name;
            string fieldType = fieldSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // 确定要生成的属性名
            string propertyName;
            var propertyNameArg = attributeData?.NamedArguments.FirstOrDefault(kvp => kvp.Key == "PropertyName").Value;
            if ( !propertyNameArg.Value.IsNull)
            {
                propertyName = (string)propertyNameArg.Value.Value!; // 使用特性指定的属性名
            }
            else
            {
                // 默认行为：假设字段名为 _name，则属性名为 Name
                propertyName = fieldName.StartsWith("_") && fieldName.Length > 1
                    ? fieldName.Substring(1)
                    : fieldName;
                propertyName = char.ToUpper(propertyName[0]) + propertyName.Substring(1); // 首字母大写
            }

            sourceBuilder.AppendLine($$"""
                        public {{fieldType}} {{propertyName}}
                        {
                            get => {{fieldName}};
                            set
                            {
                                if (!global::System.Collections.Generic.EqualityComparer<{{fieldType}}>.Default.Equals({{fieldName}}, value))
                                {
                                    {{fieldName}} = value;
                                    OnPropertyChanged(nameof({{propertyName}}));
                                }
                            }
                        }
                """);
        }
    }
}
