
# SSO、网关、公服
proxy.api.ip=${api.gateway.ip}
proxy.api.port=${api.gateway.proxy.port}
proxy.api.context=["^/sso","^/api","^/sysmanager"]

proxy.flood.ip=${api.flood.ip}
proxy.flood.port=${api.flood.proxy.port}
proxy.flood.context=["^/hjmos-wia"]

proxy.nec.ip=${api.nec.ip}
proxy.nec.port=${api.nec.proxy.port}
proxy.nec.context=["^/nec","^/hjmos-dfs","^/hjmos-wom-server","^/hjmos-basicdata-server","^/infor-notification","^/hjmos-mediacenter-admin","^/material-manage","^/hjmos-device"]